
import './styles/globals.sass'
import type { Metadata } from 'next'
import { TheFooter } from '@/components/TheFooter/TheFooter'
import { TheHeader } from '@/components/TheHeader/TheHeader'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru" translate='no'>
      <body>
        <TheHeader />
        <main>
          {children}
        </main>
        <TheFooter />
      </body>
    </html>
  )
}
